In [1]:
import pandas as pd

In [2]:
read=pd.read_csv("matches.csv")

In [3]:
read.head()
read
read.fillna('0')

id   season        city        date   match_type  player_of_match  \
0      335982  2007/08   Bangalore  2008-04-18       League      BB McCullum   
1      335983  2007/08  Chandigarh  2008-04-19       League       MEK Hussey   
2      335984  2007/08       Delhi  2008-04-19       League      MF Maharoof   
3      335985  2007/08      Mumbai  2008-04-20       League       MV Boucher   
4      335986  2007/08     Kolkata  2008-04-20       League        DJ Hussey   
...       ...      ...         ...         ...          ...              ...   
1090  1426307     2024   Hyderabad  2024-05-19       League  Abhishek Sharma   
1091  1426309     2024   Ahmedabad  2024-05-21  Qualifier 1         MA Starc   
1092  1426310     2024   Ahmedabad  2024-05-22   Eliminator         R Ashwin   
1093  1426311     2024     Chennai  2024-05-24  Qualifier 2    Shahbaz Ahmed   
1094  1426312     2024     Chennai  2024-05-26        Final         MA Starc   

                                                  venue  \
0                                 M Chinnaswamy Stadium   
1            Punjab Cricket Association Stadium, Mohali   
2                                      Feroz Shah Kotla   
3                                      Wankhede Stadium   
4                                          Eden Gardens   
...                                                 ...   
1090  Rajiv Gandhi International Stadium, Uppal, Hyd...   
1091                   Narendra Modi Stadium, Ahmedabad   
1092                   Narendra Modi Stadium, Ahmedabad   
1093           MA Chidambaram Stadium, Chepauk, Chennai   
1094           MA Chidambaram Stadium, Chepauk, Chennai   

                            team1                        team2  \
0     Royal Challengers Bangalore        Kolkata Knight Riders   
1                 Kings XI Punjab          Chennai Super Kings   
2                Delhi Daredevils             Rajasthan Royals   
3                  Mumbai Indians  Royal Challengers Bangalore   
4           Kolkata Knight Riders              Deccan Chargers   
...                           ...                          ...   
1090                 Punjab Kings          Sunrisers Hyderabad   
1091          Sunrisers Hyderabad        Kolkata Knight Riders   
1092  Royal Challengers Bengaluru             Rajasthan Royals   
1093          Sunrisers Hyderabad             Rajasthan Royals   
1094          Sunrisers Hyderabad        Kolkata Knight Riders   

                      toss_winner toss_decision                       winner  \
0     Royal Challengers Bangalore         field        Kolkata Knight Riders   
1             Chennai Super Kings           bat          Chennai Super Kings   
2                Rajasthan Royals           bat             Delhi Daredevils   
3                  Mumbai Indians           bat  Royal Challengers Bangalore   
4                 Deccan Chargers           bat        Kolkata Knight Riders   
...                           ...           ...                          ...   
1090                 Punjab Kings           bat          Sunrisers Hyderabad   
1091          Sunrisers Hyderabad           bat        Kolkata Knight Riders   
1092             Rajasthan Royals         field             Rajasthan Royals   
1093             Rajasthan Royals         field          Sunrisers Hyderabad   
1094          Sunrisers Hyderabad           bat        Kolkata Knight Riders   

       result result_margin target_runs target_overs super_over method  \
0        runs         140.0       223.0         20.0          N      0   
1        runs          33.0       241.0         20.0          N      0   
2     wickets           9.0       130.0         20.0          N      0   
3     wickets           5.0       166.0         20.0          N      0   
4     wickets           5.0       111.0         20.0          N      0   
...       ...           ...         ...          ...        ...    ...   
1090  wickets           4.0       215.0         20.0          N      

In [4]:
read.memory_usage(deep=True).sum()

np.int64(1059299)

In [5]:

read['target_runs'] = read['target_runs'].fillna(0).replace([float('inf'), -float('inf')], 0)
read['target_runs'] = read['target_runs'].astype(int)
read['result_margin'] = read['result_margin'].fillna(0).replace([float('inf'), -float('inf')], 0)
read['result_margin'] = read['result_margin'].astype(int)
read['target_overs'] = read['target_overs'].fillna(0).replace([float('inf'), -float('inf')], 0)
read['target_overs'] = read['target_overs'].astype(int)


In [6]:
read

id   season        city        date   match_type  player_of_match  \
0      335982  2007/08   Bangalore  2008-04-18       League      BB McCullum   
1      335983  2007/08  Chandigarh  2008-04-19       League       MEK Hussey   
2      335984  2007/08       Delhi  2008-04-19       League      MF Maharoof   
3      335985  2007/08      Mumbai  2008-04-20       League       MV Boucher   
4      335986  2007/08     Kolkata  2008-04-20       League        DJ Hussey   
...       ...      ...         ...         ...          ...              ...   
1090  1426307     2024   Hyderabad  2024-05-19       League  Abhishek Sharma   
1091  1426309     2024   Ahmedabad  2024-05-21  Qualifier 1         MA Starc   
1092  1426310     2024   Ahmedabad  2024-05-22   Eliminator         R Ashwin   
1093  1426311     2024     Chennai  2024-05-24  Qualifier 2    Shahbaz Ahmed   
1094  1426312     2024     Chennai  2024-05-26        Final         MA Starc   

                                                  venue  \
0                                 M Chinnaswamy Stadium   
1            Punjab Cricket Association Stadium, Mohali   
2                                      Feroz Shah Kotla   
3                                      Wankhede Stadium   
4                                          Eden Gardens   
...                                                 ...   
1090  Rajiv Gandhi International Stadium, Uppal, Hyd...   
1091                   Narendra Modi Stadium, Ahmedabad   
1092                   Narendra Modi Stadium, Ahmedabad   
1093           MA Chidambaram Stadium, Chepauk, Chennai   
1094           MA Chidambaram Stadium, Chepauk, Chennai   

                            team1                        team2  \
0     Royal Challengers Bangalore        Kolkata Knight Riders   
1                 Kings XI Punjab          Chennai Super Kings   
2                Delhi Daredevils             Rajasthan Royals   
3                  Mumbai Indians  Royal Challengers Bangalore   
4           Kolkata Knight Riders              Deccan Chargers   
...                           ...                          ...   
1090                 Punjab Kings          Sunrisers Hyderabad   
1091          Sunrisers Hyderabad        Kolkata Knight Riders   
1092  Royal Challengers Bengaluru             Rajasthan Royals   
1093          Sunrisers Hyderabad             Rajasthan Royals   
1094          Sunrisers Hyderabad        Kolkata Knight Riders   

                      toss_winner toss_decision                       winner  \
0     Royal Challengers Bangalore         field        Kolkata Knight Riders   
1             Chennai Super Kings           bat          Chennai Super Kings   
2                Rajasthan Royals           bat             Delhi Daredevils   
3                  Mumbai Indians           bat  Royal Challengers Bangalore   
4                 Deccan Chargers           bat        Kolkata Knight Riders   
...                           ...           ...                          ...   
1090                 Punjab Kings           bat          Sunrisers Hyderabad   
1091          Sunrisers Hyderabad           bat        Kolkata Knight Riders   
1092             Rajasthan Royals         field             Rajasthan Royals   
1093             Rajasthan Royals         field          Sunrisers Hyderabad   
1094          Sunrisers Hyderabad           bat        Kolkata Knight Riders   

       result  result_margin  target_runs  target_overs super_over method  \
0        runs            140          223            20          N    NaN   
1        runs             33          241            20          N    NaN   
2     wickets              9          130            20          N    NaN   
3     wickets              5          166            20          N    NaN   
4     wickets              5          111            20          N    NaN   
...       ...            ...          ...           ...        ...    ...   
1090  wickets              4          215       

In [7]:
df=pd.read_csv("matches.csv",usecols=['team1','team2','toss_winner','toss_decision','venue','winner'])
df=df.dropna(subset=['winner'])
df=df.reset_index(drop=True)

In [8]:
print("shape:",df.shape)
df.head()

shape: (1090, 6)


venue                        team1  \
0                       M Chinnaswamy Stadium  Royal Challengers Bangalore   
1  Punjab Cricket Association Stadium, Mohali              Kings XI Punjab   
2                            Feroz Shah Kotla             Delhi Daredevils   
3                            Wankhede Stadium               Mumbai Indians   
4                                Eden Gardens        Kolkata Knight Riders   

                         team2                  toss_winner toss_decision  \
0        Kolkata Knight Riders  Royal Challengers Bangalore         field   
1          Chennai Super Kings          Chennai Super Kings           bat   
2             Rajasthan Royals             Rajasthan Royals           bat   
3  Royal Challengers Bangalore               Mumbai Indians           bat   
4              Deccan Chargers              Deccan Chargers           bat   

                        winner  
0        Kolkata Knight Riders  
1          Chennai Super Kings  
2             Delhi Daredevils  
3  Royal Challengers Bangalore  
4        Kolkata Knight Riders

In [10]:
from sklearn .preprocessing import LabelEncoder
df_encoded=df.copy()
le=LabelEncoder()
col_to_encode=['team1','team2','toss_winner','toss_decision','venue','winner']

In [11]:
df.tail(10)

venue  \
1080                   M Chinnaswamy Stadium, Bengaluru   
1081                        Arun Jaitley Stadium, Delhi   
1082                Barsapara Cricket Stadium, Guwahati   
1083                           Wankhede Stadium, Mumbai   
1084                   M Chinnaswamy Stadium, Bengaluru   
1085  Rajiv Gandhi International Stadium, Uppal, Hyd...   
1086                   Narendra Modi Stadium, Ahmedabad   
1087                   Narendra Modi Stadium, Ahmedabad   
1088           MA Chidambaram Stadium, Chepauk, Chennai   
1089           MA Chidambaram Stadium, Chepauk, Chennai   

                            team1                  team2  \
1080  Royal Challengers Bengaluru         Delhi Capitals   
1081               Delhi Capitals   Lucknow Super Giants   
1082             Rajasthan Royals           Punjab Kings   
1083         Lucknow Super Giants         Mumbai Indians   
1084  Royal Challengers Bengaluru    Chennai Super Kings   
1085                 Punjab Kings    Sunrisers Hyderabad   
1086          Sunrisers Hyderabad  Kolkata Knight Riders   
1087  Royal Challengers Bengaluru       Rajasthan Royals   
1088          Sunrisers Hyderabad       Rajasthan Royals   
1089          Sunrisers Hyderabad  Kolkata Knight Riders   

               toss_winner toss_decision                       winner  
1080        Delhi Capitals         field  Royal Challengers Bengaluru  
1081  Lucknow Super Giants         field               Delhi Capitals  
1082      Rajasthan Royals           bat                 Punjab Kings  
1083        Mumbai Indians         field         Lucknow Super Giants  
1084   Chennai Super Kings         field  Royal Challengers Bengaluru  
1085          Punjab Kings           bat          Sunrisers Hyderabad  
1086   Sunrisers Hyderabad           bat        Kolkata Knight Riders  
1087      Rajasthan Royals         field             Rajasthan Royals  
1088      Rajasthan Royals         field          Sunrisers Hyderabad  
1089   Sunrisers Hyderabad           bat        Kolkata Knight Riders

In [17]:
for col in col_to_encode:
    df_encoded[col]=le.fit_transform(df_encoded[col])

print(df_encoded.tail(10))
df_encoded

      venue  team1  team2  toss_winner  toss_decision  winner
1080     24     17      2            2              1      17
1081      1      2      9            9              1       2
1082      3     13     12           13              0      12
1083     56      9     10           10              1       9
1084     24     17      0            0              1      17
1085     43     12     18           12              0      18
1086     32     18      8           18              0       8
1087     32     17     13           13              1      13
1088     28     18     13           13              1      18
1089     28     18      8           18              0       8


venue  team1  team2  toss_winner  toss_decision  winner
0        23     16      8           16              1       8
1        40      6      0            0              0       0
2        16      3     13           13              0       3
3        55     10     16           10              0      16
4        14      8      1            1              0       8
...     ...    ...    ...          ...            ...     ...
1085     43     12     18           12              0      18
1086     32     18      8           18              0       8
1087     32     17     13           13              1      13
1088     28     18     13           13              1      18
1089     28     18      8           18              0       8

[1090 rows x 6 columns]

In [30]:
from sklearn.model_selection import train_test_split
X=df_encoded.drop('winner',axis=1)
y=df_encoded['winner']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=42)

print("traning set:",X_train.shape)
print("test set:",X_test.shape)

traning set: (545, 5)
test set: (545, 5)


In [31]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred=model.predict(X_test)

accuracy=accuracy_score(y_test,y_pred)
print(f"model accuracy:{accuracy:.2%}")

cm=confusion_matrix(y_test,y_pred)
print("\nconfusion Matrix:")
print(cm)

model accuracy:47.34%

confusion Matrix:
[[52  0  3  2  0  1  1  0  3  1  6  1  0  3  0  0  3  0  1]
 [ 0  5  1  3  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 3  1  4  0  0  0  1  0  1  1  3  0  2  2  0  0  1  0  2]
 [ 3  2  0  6  0  0  4  0  5  0  6  1  0  2  1  0  2  0  0]
 [ 0  0  0  1  3  0  0  0  2  0  1  0  0  0  0  1  1  0  0]
 [ 3  1  1  0  1  3  0  0  2  0  0  0  0  1  0  0  1  0  2]
 [ 4  2  1  1  2  0 13  0  3  0  5  1  0  6  0  0  9  0  3]
 [ 0  1  0  0  0  0  1  0  1  0  0  0  0  1  0  0  0  0  0]
 [ 6  1  1  1  0  0  8  0 29  1  6  1  0  1  0  1  5  1  2]
 [ 0  0  1  0  0  0  0  0  2  4  0  0  0  1  0  0  0  1  0]
 [ 3  0  2  1  0  1  4  0  3  1 47  0  1  2  0  0  1  0  3]
 [ 0  0  0  1  0  0  0  0  0  0  1  2  0  1  0  0  0  0  0]
 [ 3  0  0  0  0  1  0  0  1  1  0  0  3  0  0  0  0  0  2]
 [ 7  2  3  3  0  0  1  0  3  0  5  0  0 22  0  0  6  0  4]
 [ 0  0  0  0  0  0  0  0  1  0  2  0  0  0  2  0  1  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  1  0  1]

In [37]:
import numpy as np
new=np.array([32,17,12,17,0]).reshape(1,-1)
pre_enc_win=model.predict(new)[0]

C:\Users\KUSHAGRA MAHALAHA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [1]:
from sklearn.preprocessing import LabelEncoder
le_target = LabelEncoder()
le_target.fit(df['winner'])

predicted_winner = le_target.inverse_transform([pre_enc_win])[0]

print(f"🔮 Predicted Winner: {predicted_winner}")

NameError: name 'df' is not defined